### ISSUE TITLE
Docker Installation: manifest unknown

### ISSUE THREAD

**Issue by trleith** [pmdroid/plexamp-headless-docker#2]
I'm afraid I don't know what to do. I wanted to use Docker for this because I have another Docker app on another machine and prefer to deepen my understanding of Docker to adding another framework (podman) to the list of things I'm going to forget how to use. I've never used docker-compose, for example.

is there a way to get a list of manifests at ghcr.io/pmdroid? I guess I'm missing the current name.

Hints appreciated...

     t

I have 
```
root@plex-player:/opt/plexamp# docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~20.04.1
root@plex-player:/opt/plexamp# docker-compose --version
Docker Compose version v2.12.2
root@plex-player:/opt/plexamp# docker-compose -f /opt/plexamp/plexamp-docker-compose.yml up -d
[+] Running 0/1
 ⠿ lms Error                                                               0.5s
Error response from daemon: manifest unknown
```
### plexamp-docker-compose.yml 

```
root@plex-player:/opt/plexamp# cat plexamp-docker-compose.yml
version: "1.0"
services:
  lms:
    container_name: plexamp
    privileged: true
    network_mode: "host"
    image: ghcr.io/pmdroid/plexamp-headless-docker:amd64-461
    volumes:
      - /opt/plexamp/docker/:/home/plexamp:rw
      - /run:/run:rw
    restart: unless-stopped
```
